--- #YAML:1.0
name:                POE-Component-RSSAggregator
version:             1.11
abstract:            Watch Muliple RSS Feeds for New Headlines
license:             perl
author:              
    - Jeff Bisbee <jbisbee@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    HTTP::Request:                 1.3
    POE:                           0
    POE::Component::Client::DNS:   0.98
    POE::Component::Client::HTTP:  0.51
    Test::More:                    0
    XML::RSS::Feed:                0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
