# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-RSSAggregator
version:      0.3
version_from: lib/POE/Component/RSSAggregator.pm
installdirs:  site
requires:
    HTTP::Request:                 1.3
    POE::Component::Client::DNS:   0.98
    POE::Component::Client::HTTP:  0.51
    XML::RSS::Feed:                0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.24
